name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Infrastructure-deploy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Apply Terraform
        id:   terraform-apply
        run: |
          cd static-website-infra/
          terraform init
          # terraform apply -auto-approve
          terraform destroy -auto-approve
